theme: minima
title: Dam.OS - Launching x86_64 Applications on ARM
url: https://damos.dev/
author: Damian Wuorio
avatar: https://github.com/SMGXSCRIPTS/damos-pkg-repo/raw/main/lib/DAM.OS-LOGO_V3.png
round-avatar: true
